<h2 style="color: orangered; background-color: bisque;"> <b> Project:1 </b> Data Cleaning with Python</h2>

> <h3>Import Required Libraries</h3>

In [61]:
import pandas as pd
import numpy as np
from IPython.display import display, Markdown

> <h3>Load Dataset</h3>

In [62]:
data=pd.read_csv("Dataset for Data Analytics - Sheet1.csv")

> <h3>Dataset View</h3>

In [63]:
data.shape

(1200, 14)

In [64]:
data.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [65]:
data.tail()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [66]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   object
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: float64(2), int64(2), object(10)
memory usage: 131.4+ KB

In [67]:
data.sample(10)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
276,ORD200276,2025-03-29,C99050,Printer,2,600.57,654 Main St,Debit Card,Returned,TRK56927089,3,WINTER15,Instagram,1201.14
1024,ORD201024,2024-01-29,C90612,Chair,3,367.75,731 Main St,Cash,Pending,TRK93022878,7,FREESHIP,Facebook,1103.25
966,ORD200966,2025-05-20,C58503,Monitor,5,280.52,290 Main St,Credit Card,Cancelled,TRK12981657,7,WINTER15,Facebook,1402.60
1172,ORD201172,2025-02-04,C28828,Desk,3,131.96,745 Main St,Credit Card,Pending,TRK32550359,8,NaN,Instagram,395.88
430,ORD200430,2023-06-07,C87448,Phone,1,450.07,433 Main St,Gift Card,Shipped,TRK44134016,6,FREESHIP,Google,450.07
679,ORD200679,2023-02-02,C40798,Tablet,3,360.66,304 Main St,Online,Returned,TRK66106697,5,FREESHIP,Instagram,1081.98
578,ORD200578,2024-10-10,C50415,Monitor,5,566.07,587 Main St,Credit Card,Delivered,TRK41345634,6,SAVE10,Instagram,2830.35
1161,ORD201161,2023-10-16,C32570,Phone,1,11.39,826 Main St,Cash,Cancelled,TRK35969968,6,WINTER15,Email,11.39
766,ORD200766,2023-01-22,C91454,Printer,2,278.88,494 Main St,Debit Card,Pending,TRK99985340,3,FREESHIP,Referral,557.76
1154,ORD201154,2025-06-11,C53631,Monitor,3,198.63,593 Main St,Cash,Pending,TRK67589167,8,SAVE10,Instagram,595.89

> <h3>Check for Duplicate Rows</h3>

In [68]:
data.duplicated().sum()

np.int64(0)

> <h3>Check for Missing Values</h3>

In [69]:
missing_value=data.isnull().sum().sum()
if missing_value>0:
    display(Markdown('<h2 style="color: red;"> Missing Values Found</h2>'))
    print(data.isnull().sum())
else:
    display(Markdown('<h2 style="color: green;"> Missing Values Not Found </h2>'))

<h2 style="color: red;"> Missing Values Found</h2>

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

> <h3>Impute Missing Values</h3>

In [70]:
data["CouponCode"].unique()

array(['SAVE10', 'FREESHIP', nan, 'WINTER15'], dtype=object)

In [71]:
data["CouponCode"]=data["CouponCode"].fillna("No_Coupon")

In [81]:
missing_value=data.isnull().sum().sum()
if missing_value>0:
    display(Markdown('<h2 style="color: red;"> Missing Values </h2>'))
    print(data.isnull().sum())
else:
    display(Markdown('<h2 style="color: green;">Missing Values Removed</h2>'))
    print(data.isnull().sum())

display(Markdown('<h3 style="color: green;"> Imputation Completed! </h3>'))
display(Markdown(f'<h4 style="color: yellow;"> Remaining null values in <b>CouponCode</b>: {data["CouponCode"].isnull().sum()}</h4>'))

<h2 style="color: green;">Missing Values Removed</h2>

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

<h3 style="color: green;"> Imputation Completed! </h3>

<h4 style="color: yellow;"> Remaining null values in <b>CouponCode</b>: 0</h4>

> <h3>Handling Extra Spaces</h3>

In [73]:
display(Markdown('<h2 style="color: purple;">Remove extra Spaces done!</h2>'))
categorical_cols = ['Product', 'PaymentMethod', 'OrderStatus', 'ReferralSource']
for col in categorical_cols:
    data[col] = data[col].astype(str).str.strip()

<h2 style="color: purple;">Remove extra Spaces done!</h2>

> <h3>Save Cleaned Dataset</h3>

In [ ]:
clean_data=data.to_csv("clean_data.csv")

In [80]:
pd.read_csv("clean_data.csv").head()

,Unnamed: 0,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

> <h3>End........</h3>